---

# clone + update
- name: clone gitlab
  git:
    repo: 'https://gitlab.com/gitlab-org/gitlab-ee.git'
    dest: /home/git/gitlab
    version: "{{ gitlab_version }}"
    update: yes
    force: yes
  become: yes
  become_user: git
